### PR TITLE
Remove broken link to "K-Java: A Complete Semantics of Java"

### PR DESCRIPTION
**Pull request by yallop**
/cc @denis-bogdanas: is there an online copy of the paper that we can link to?

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
Yes, here:
https://fmse.info.uaic.ro/publications/192/

**Comment by yallop** [comment]
Thanks!

**Comment by denis-bogdanas** [comment]
By the way, the paper has just 2 authors, please remove the middle one.

**Comment by yallop** [comment]
Fixed (0773511a).

**Pull request merged**
